**Introduction to Pandas**

**Pandas Python Library**

**Introduction to Pandas**

Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

**Key features and functionalities of Pandas include: Data Structures:**

Pandas introduces two primary data structures:

**Series:** A one-dimensional labeled array capable of holding any data type. It can be thought of as a single column in a spreadsheet.

**DataFrame:** A two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table, providing a powerful way to represent and manipulate tabular data.

**What is pandas used for?**

pandas is used throughout the data analysis workflow. With pandas, you can:

1.Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more.
2.Clean datasets, for example, by dealing with missing values.
3.Tidy datasets by reshaping their structure into a suitable format for analysis.
4.Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more.
5.Visualize datasets and uncover insights.

**Importing to Pandas**

In [ ]:
import pandas as pd

**Importing CSV files**

Use **read_csv()** with the path to the CSV file to read a comma-separated values file

In [5]:
df=pd.read_excel("/content/student details.xlsx")

In [6]:
df.head()

,Student Name,Roll no,Branch,Subjects,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,Java,Python,Maths,chemistry,Physics
1,Aruna,11.0,CSM,78,67,65,80,79
2,Dev,12.0,CSM,90,80,78,90,76
3,Soniya,13.0,CSM,95,70,67,70,87
4,Rockey,14.0,CSD,85,90,70,90,76

In [7]:
df.tail()

,Student Name,Roll no,Branch,Subjects,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
8,Vijay,18.0,CSO,80,60,95,79,100
9,Naveen,19.0,CSO,85,65,95,90,90
10,Guna,20.0,CSE,88,70,94,56,80
11,Ravi,21.0,CSE,75,75,98,88,80
12,Anitha,22.0,CSE,60,85,58,88,90

In [8]:
df.describe()

         Roll no
count  12.000000
mean   16.500000
std     3.605551
min    11.000000
25%    13.750000
50%    16.500000
75%    19.250000
max    22.000000

In [10]:
df.columns

Index(['Student Name', 'Roll no', 'Branch', 'Subjects', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='object')

**Importing Textfiles**